spring.application.name=dtcllshop-be
server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/dtcllshop
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phuocloi4102@gmail.com
spring.mail.password=ekvsqwr1qrwecsqp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

jwt.password.reset.secret=c8e09fddda9e192d16c485affabc61c9f4bca77a60c19d448f3a6e8475b9f0a4e0d1f69bca8d21f1123b8f0f8a0b8d12
jwt.password.reset.expiration=900000
gemini.api.key=xxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Sepay thanh toan
sepay.api-key=DTCLL_SHOP_KEY